version: '3'

services:
  proxy:
    image: traefik:v3.3
    restart: always
    mem_limit: 512m
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      GANDIV5_PERSONAL_ACCESS_TOKEN: "${GANDIV5_PERSONAL_ACCESS_TOKEN}"
    volumes:
      - /home/rkd/traefik/:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock

  portainer:
    container_name: portainer
    mem_limit: 512m
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.docker/portainer_data:/data"
    image: "portainer/portainer-ee:lts"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.h.rkd.pw`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    mem_limit: 6g
    ports:
      - "8096:8096"
    volumes:
      - /home/rkd/.docker/jellyfin/config:/config
      - /home/rkd/.docker/jellyfin/cache:/cache
      - type: bind
        source: /home/rkd/.nas
        target: /nas
    restart: 'always'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://jf.h.rkd.pw
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jf.h.rkd.pw`) || Host(`jellyfin.h.rkd.pw`) || Host(`jellyfin.local`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    mem_limit: 512m
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /home/rkd/.docker/jackett/data:/config
      - /home/rkd/.nas/Downloads:/downloads
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.h.rkd.pw`)"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    mem_limit: 512m
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/rkd/.docker/radarr/data:/config
      - /home/rkd/.nas:/movies #optional
      - /home/rkd/.nas:/nas
      - /home/rkd/.nas/Downloads:/downloads #optional
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.h.rkd.pw`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "compote.fav=true"

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    mem_limit: 1g
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /home/rkd/.docker/deluge/config:/config
      - /home/rkd/.nas:/nas
      - /home/rkd/.nas/Downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deluge.rule=Host(`deluge.h.rkd.pw`)"
      - "traefik.http.services.deluge.loadbalancer.server.port=8112"
      - "compote.fav=true"

  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: always
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/harakas/frigate:latest-rocm
    shm_size: "512mb" # update for your cameras based on calculation above
    mem_limit: 3g
    mem_reservation: 3g
    security_opt:
      - apparmor=unconfined
      - systempaths=unconfined
    devices:
      - /dev/dri
      - /dev/kfd:/dev/kfd
      - /dev/dma_heap
      - /dev/rga
      - /dev/mpp_service
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/rkd/.docker/frigate/config:/config
      - /home/rkd/.docker/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 500000000
    ports:
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - FRIGATE_RTSP_PASSWORD=frigate
      - LIBVA_DRIVER_NAME=radeonsi
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frigate.rule=Host(`frigate.h.rkd.pw`)"
      - "traefik.http.services.frigate.loadbalancer.server.port=5000"
      - "compote.fav=true"

  librechat-api:
    container_name: LibreChat
    depends_on:
      - librechat-mongodb
      - librechat-rag_api
    image: ghcr.io/danny-avila/librechat-dev:latest
    mem_limit: 512m
    restart: always
    user: "1000:1000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://librechat-mongodb:27017/LibreChat
      - MEILI_HOST=http://librechat-meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://librechat-rag_api:${RAG_PORT:-8000}
    volumes:
      - /home/rkd/.docker/librechat/.env:/app/.env:ro
      - /home/rkd/.docker/librechat/librechat.yaml:/app/librechat.yaml:ro
      - /home/rkd/.docker/librechat/images:/app/client/public/images
      - /home/rkd/.docker/librechat/uploads:/app/uploads
      - /home/rkd/.docker/librechat/logs:/app/api/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librechat.rule=Host(`librechat.h.rkd.pw`)"
      - "traefik.http.services.librechat.loadbalancer.server.port=3080"
      - "compote.fav=true"

  librechat-mongodb:
    container_name: chat-mongodb
    image: mongo
    restart: always
    mem_limit: 512m
    user: "1000:1000"
    volumes:
      - /home/rkd/.docker/librechat/data-node:/data/db
    command: mongod --noauth

  librechat-meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always
    mem_limit: 512m
    user: "1000:1000"
    environment:
      - MEILI_HOST=http://librechat-meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-}
    volumes:
      - /home/rkd/.docker/librechat/meili_data_v1.12:/meili_data

  librechat-vectordb:
    container_name: vectordb
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    mem_limit: 512m
    restart: always
    volumes:
      - /home/rkd/.docker/librechat/pgdata2:/var/lib/postgresql/data

  librechat-rag_api:
    container_name: rag_api
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=librechat-vectordb
      - RAG_PORT=${RAG_PORT:-8000}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    restart: always
    depends_on:
      - librechat-vectordb

  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    mem_limit: 512m
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
    volumes:
      - ./.docker/kavita/config:/config
      - ./.docker/kavita/data:/data #optional
      - ./.docker/nextcloud/data/data/ilvar/files/Books:/data/nextcloud/Books
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kavita.rule=Host(`kavita.h.rkd.pw`) || Host(`kavita.d.z85`)"
      - "traefik.http.services.kavita.loadbalancer.server.port=5000"

  hoarder-web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: always
    mem_limit: 1g
    volumes:
      - ./.docker/hoarder/data:/data
    environment:
      MEILI_ADDR: http://hoarder-meilisearch:7700
      BROWSER_WEB_URL: http://hoarder-chrome:9222
      OPENAI_API_KEY: "${OPENAI_API_KEY:-}"
      DATA_DIR: /data
      NEXTAUTH_SECRET: jedijedi
      MEILI_MASTER_KEY: jedijedi
      NEXTAUTH_URL: https://hoarder.h.rkd.pw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hoarder.rule=Host(`hoarder.h.rkd.pw`) || Host(`hoarder.d.z85`)"
      - "traefik.http.services.hoarder.loadbalancer.server.port=3000"
      - "compote.fav=true"

  hoarder-chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: always
    mem_limit: 1g
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars

  hoarder-meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: always
    mem_limit: 512m
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: jedijedi
    volumes:
      - ./.docker/hoarder/meilisearch:/meili_data

  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: always
    mem_limit: 512m
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Dublin
    volumes:
      - /home/rkd/.docker/blocky/config.yaml:/app/config.yml

  compote:
    image: r.c.rkd.pw/compote2:latest
    build: ./compote2
    container_name: compote2
    mem_limit: 512m
    volumes:
      - /home/rkd/.docker/compote/config.yaml:/app/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/rkd/.docker/compote:/app/data
    environment:
      - CAPROVER_PASSWORD=${CAPROVER_PASSWORD:-}
      - CAPROVER_URL=https://captain.c.rkd.pw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.compote.rule=Host(`compote.h.rkd.pw`) || Host(`compote.docker.z85`) || Host(`c.h.rkd.pw`)"
      - "traefik.http.services.compote.loadbalancer.server.port=3000"

  homeassistant:
    container_name: home-assistant
    restart: always
    image: homeassistant/home-assistant:latest
    mem_limit: 1g
    user: 1000:1000
    volumes:
      - /home/rkd/.docker/hass-config:/config
      - /home/rkd/.docker/hass_media:/media
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    ports:
      - 8123:8123
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ha.rule=Host(`ha.h.rkd.pw`) || Host(`ha.z85`)"
      - "traefik.http.services.ha.loadbalancer.server.port=8123"
      - "compote.fav=true"

  nodered:
    container_name: node-red-1
    restart: always
    image: nodered/node-red
    mem_limit: 512m
    depends_on:
      - "homeassistant"
    user: 1000:1000
    privileged: true
    volumes:
      - /home/rkd/.docker/node-red-1/user:/data
      - /home/rkd/.docker/hass_media:/hass_media
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodered.rule=Host(`nodered.h.rkd.pw`) || Host(`n.h.rkd.pw`) || Host(`nodered.z85`)"
      - "traefik.http.services.nodered.loadbalancer.server.port=1880"
      - "traefik.port=1880"

  redis:
    image: "redis:alpine"
    restart: always
    mem_limit: 512m
    volumes:
      - ./redis/data:/data
    ports:
      - "6379:6379"

  photoprism:
    # Use photoprism/photoprism:preview instead for testing preview builds:
    image: photoprism/photoprism:latest
    # Only enable automatic restarts once your installation is properly
    # configured as it otherwise may get stuck in a restart loop:
    # https://docs.photoprism.org/getting-started/faq/#why-is-photoprism-getting-stuck-in-a-restart-loop
    # restart: always
    restart: always
    mem_limit: 1g
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    user: 1000:1000
    environment:
      PUID: 1000
      PGID: 1000
      PHOTOPRISM_ADMIN_PASSWORD: "${PHOTOPRISM_ADMIN_PASSWORD:-}"          # PLEASE CHANGE: Your initial admin password (min 4 characters)
      PHOTOPRISM_HTTP_PORT: 2342                     # Built-in Web server port
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # Improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "true"                     # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                   # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "true"               # Enables experimental features
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # Disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # Disables Settings in Web UI
      PHOTOPRISM_DISABLE_TENSORFLOW: "true"         # Disables using TensorFlow for image classification
      PHOTOPRISM_DARKTABLE_PRESETS: "false"          # Enables Darktable presets and disables concurrent RAW conversion
      PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "false"                 # Allow uploads that MAY be offensive
      # PHOTOPRISM_DATABASE_DRIVER: "sqlite"         # SQLite is an embedded database that doesn't require a server
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # Use MariaDB (or MySQL) instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb-photoprism:3306"     # MariaDB database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB database user name
      PHOTOPRISM_DATABASE_PASSWORD: "${PHOTOPRISM_DATABASE_PASSWORD:-}"       # MariaDB database user password
      PHOTOPRISM_SITE_URL: "http://photos.z85/"  # Public PhotoPrism URL
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
      PHOTOPRISM_AUTO_INDEX: 60
      PHOTOPRISM_AUTO_IMPORT: 60
      PHOTOPRISM_THUMB_UNCACHED: "true"
    volumes:
      # Your photo and video files ([local path]:[container path]):
      - "/home/rkd/.docker/photoprism-originals:/photoprism/originals"
      - "/home/rkd/.docker/nextcloud/data/data/ilvar/files/InstantUpload/Camera:/photoprism/originals/Camera:ro"
      - "/home/rkd/.docker/nextcloud/data/data/ilvar/files/InstantUpload/2022:/photoprism/originals/2022:ro"
      - "/home/rkd/.docker/nextcloud/data/data/ilvar/files/InstantUpload/2023:/photoprism/originals/2023:ro"
      - "/home/rkd/.docker/nextcloud/data/data/ilvar/files/InstantUpload/OpenCamera:/photoprism/originals/OpenCamera:ro"
      - "/home/rkd/.docker/photoprism-storage:/photoprism/storage"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:photos.z85"
      - "traefik.port=2342"
      - "traefik.http.routers.ph.rule=Host(`photos.h.rkd.pw`) || Host(`ph.h.rkd.pw`) || Host(`photos.z85`)"
      - "traefik.http.services.ph.loadbalancer.server.port=2342"
      - "compote.fav=true"

  mariadb-photoprism:
    image: mariadb:10.5
    restart: always
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes: # Don't remove permanent storage for index database files!
      - "/home/rkd/.docker/photoprism-database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: jedi8947
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: jedi8947

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  teslamate:
    image: teslamate/teslamate:1.33.0
    restart: always
    mem_limit: 512m
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=teslamate-database
      - MQTT_HOST=192.168.1.123
      - ENCRYPTION_KEY=${TESLAMATE_ENCRYPTION_KEY:-}
    volumes:
      - /home/rkd/.docker/teslamate/import:/opt/app/import
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tesla.rule=Host(`tesla.h.rkd.pw`) || Host(`tesla.z85`) || Host(`t.h.rkd.pw`)"
      - "traefik.http.services.teslamate.loadbalancer.server.port=4000"
      - "compote.fav=true"

  teslamate-database:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=teslamate
    volumes:
      - /home/rkd/.docker/teslamate/db:/var/lib/postgresql/data

  teslamate-grafana:
    image: teslamate/grafana:latest
    restart: always
    mem_limit: 512m
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=teslamate-database
    ports:
      - 3000:3000
    volumes:
      - /home/rkd/.docker/teslamate/grafana-data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teslamate-grafana.rule=Host(`teslagraphs.h.rkd.pw`)"
      - "traefik.http.services.teslamate-grafana.loadbalancer.server.port=3000"

  paperless-redis:
    image: redis:6.0
    restart: always

  paperless-webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: always
    mem_limit: 512m
    volumes:
        - /home/rkd/.docker/paperless/data:/usr/src/paperless/data
        - /home/rkd/.docker/paperless/media:/usr/src/paperless/media
        - /home/rkd/.docker/paperless/export:/export
        - /home/rkd/.docker/paperless/consume:/consume
    environment:
      - PAPERLESS_OCR_LANGUAGES=eng
      - TZ=Europe/Dublin
      - PAPERLESS_USE_SSL=false
      - PAPERLESS_FORGIVING_OCR=true
      - PAPERLESS_REDIS=redis://paperless-redis:6379
      - PAPERLESS_OCR_MODE=skip
      - PAPERLESS_CONSUMER_DISABLE=true
      - PAPERLESS_WEBSERVER_WORKERS=4
      - PAPERLESS_URL=http://docs.h.rkd.pw
      - USE_X_FORWARD_HOST=true
      - USE_X_FORWARD_PORT=true
      - PAPERLESS_PROXY_SSL_HEADER='["HTTP_X_FORWARDED_PROTO", "https"]'
      - PAPERLESS_SECRET_KEY=ilvar
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docs.rule=Host(`docs.h.rkd.pw`) || Host(`d.h.rkd.pw`) || Host(`docs.z85`)"
      - "traefik.http.services.docs.loadbalancer.server.port=8000"
      - "compote.fav=true"

  nextcloud-db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    user: 1000:1000
    volumes:
      - /home/rkd/.docker/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - PUID=1000
      - PGID=1000

  nextcloud-app:
    image: nextcloud
    restart: always
    mem_limit: 512m
    depends_on:
      - nextcloud-db
    volumes:
      - /home/rkd/.docker/nextcloud/data:/var/www/html
    user: 1000:1000
    environment:
      - PUID=1000
      - PGID=1000
      - NEXTCLOUD_ADMIN_USER=ilvar
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:-}
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.h.rkd.pw,nextcloud.z85,nc.h.rkd.pw
      - OVERWRITEHOST=nextcloud.h.rkd.pw
      - OVERWRITEPROTOCOL=https
      - VIRTUAL_HOST=nextcloud.h.rkd.pw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nc.rule=Host(`nextcloud.h.rkd.pw`) || Host(`nextcloud.z85`) || Host(`nc.h.rkd.pw`)"
      - "traefik.http.services.nc.loadbalancer.server.port=80"

  gitea-db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - /home/rkd/.docker/gitea/db:/var/lib/postgresql/data

  gitea:
    image: gitea/gitea:1.14.4
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - LOCAL_ROOT_URL=https://gitea.h.rkd.pw/
    restart: always
    depends_on:
      - gitea-db
    volumes:
      - /home/rkd/.docker/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "222:22"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`gitea.h.rkd.pw`)"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "compote.fav=true"

  kuma:
    image: louislam/uptime-kuma:latest
    restart: always
    mem_limit: 512m
    volumes:
      - /home/rkd/.docker/kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    dns:
      - 192.168.1.123
      - 192.168.1.122
    extra_hosts:
      - "jackett.z85:192.168.1.123"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kuma.rule=Host(`kuma.h.rkd.pw`) || Host(`k.h.rkd.pw`)"
      - "traefik.http.services.kuma.loadbalancer.server.port=3001"

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    group_add:
      - video
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    volumes:
      - /home/rkd/.docker/immich/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Dublin
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - DB_HOSTNAME=immich-database
    depends_on:
      - immich-redis
      - immich-database
    restart: always
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`immich.h.rkd.pw`)"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    group_add:
      - video
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    volumes:
      - /home/rkd/.docker/immich/model-cache:/cache
    restart: always
    healthcheck:
      disable: false

  immich-redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  immich-database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /home/rkd/.docker/immich/postgres:/var/lib/postgresql/data
    restart: always