blocky:
  enabled: true
  image:
    repository: spx01/blocky
    tag: latest
  timezone: Europe/Dublin
  ports:
    dns:
      tcp: 53
      udp: 53
    http: 4000
portainer:
  enabled: true
  image:
    repository: portainer/portainer-ce
    tag: latest
  resources:
    limits:
      memory: 64Mi
    requests:
      memory: 32Mi
  storage:
    data: portainer-data
  ingress:
    enabled: true
    hosts:
    - portainer.h.rkd.pw
    - portainer.k.rkd.pw
    servicePort: 9000
jackett:
  enabled: true
  image:
    repository: lscr.io/linuxserver/jackett
    tag: latest
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
  environment:
    PUID: 1000
    PGID: 1000
    TZ: Etc/UTC
    AUTO_UPDATE: 'true'
  storage:
    config: jackett-data
    downloads: jackett-downloads
  ingress:
    enabled: true
    hosts:
    - jackett.h.rkd.pw
    - jackett.k.rkd.pw
    servicePort: 9117
radarr:
  enabled: true
  image:
    repository: lscr.io/linuxserver/radarr
    tag: latest
  resources:
    limits:
      memory: 768Mi
    requests:
      memory: 512Mi
  environment:
    PUID: 1000
    PGID: 1000
    TZ: Etc/UTC
  storage:
    config: radarr-data
    movies: radarr-movies
    nas: radarr-nas
    downloads: radarr-downloads
  ingress:
    enabled: true
    hosts:
    - radarr.h.rkd.pw
    - radarr.k.rkd.pw
    servicePort: 7878
jellyfin:
  enabled: true
  image:
    repository: jellyfin/jellyfin
    tag: latest
  resources:
    limits:
      memory: 768Mi
    requests:
      memory: 512Mi
  user: 1000:1000
  environment:
    JELLYFIN_PublishedServerUrl: https://jf.h.rkd.pw
  ports:
    http: 8096
  storage:
    config: jellyfin-config
    cache: jellyfin-cache
    nas: jellyfin-nas
  ingress:
    enabled: true
    hosts:
    - jf.h.rkd.pw
    - jellyfin.h.rkd.pw
    - jellyfin.k.rkd.pw
    - jellyfin.local
    servicePort: 8096
deluge:
  enabled: true
  image:
    repository: lscr.io/linuxserver/deluge
    tag: latest
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
  environment:
    PUID: 1000
    PGID: 1000
    TZ: Etc/UTC
    DELUGE_LOGLEVEL: error
  ports:
    bittorrent:
      tcp: 6881
      udp: 6881
    daemon: 58846
  storage:
    config: deluge-config
    nas: deluge-nas
    downloads: deluge-downloads
  ingress:
    enabled: true
    hosts:
    - deluge.h.rkd.pw
    - deluge.k.rkd.pw
    servicePort: 8112
homeassistant:
  enabled: true
  image:
    repository: homeassistant/home-assistant
    tag: latest
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
  user: 0:0
  privileged: true
  ports:
    http: 8123
  storage:
    config: homeassistant-config
    media: homeassistant-media
  ingress:
    enabled: true
    hosts:
    - ha.h.rkd.pw
    - ha.k.rkd.pw
    - ha.z85
    servicePort: 8123
frigate:
  enabled: true
  image:
    repository: ghcr.io/harakas/frigate
    tag: latest-rocm
  resources:
    limits:
      memory: 3Gi
    requests:
      memory: 1536Mi
  privileged: true
  ports:
    rtsp: 8554
    webrtc:
      tcp: 8555
      udp: 8555
  environment:
    FRIGATE_RTSP_PASSWORD: frigate
    LIBVA_DRIVER_NAME: radeonsi
  storage:
    cacheSize: 500Mi
  ingress:
    enabled: true
    hosts:
    - frigate.h.rkd.pw
    servicePort: 5000
nodered:
  enabled: true
  image:
    repository: nodered/node-red
    tag: latest
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
  user: 1000:1000
  privileged: true
  ports:
    http: 1880
  ingress:
    enabled: true
    hosts:
    - nodered.h.rkd.pw
    - n.h.rkd.pw
    - nodered.z85
    servicePort: 1880
hoarder:
  enabled: true
  web:
    image:
      repository: ghcr.io/hoarder-app/hoarder
      tag: release
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 256Mi
    environment:
      MEILI_ADDR: http://hoarder-meilisearch:7700
      BROWSER_WEB_URL: http://hoarder-chrome:9222
      DATA_DIR: /data
      NEXTAUTH_URL: https://hoarder.h.rkd.pw
    storage:
      data: hoarder-data
  secrets:
    nextauthSecret: jedijedi
    meiliMasterKey: jedijedi
  ingress:
    enabled: true
    hosts:
    - hoarder.h.rkd.pw
    - hoarder.k.rkd.pw
    - hoarder.d.z85
    servicePort: 3000
  chrome:
    image:
      repository: gcr.io/zenika-hub/alpine-chrome
      tag: '123'
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 256Mi
  meilisearch:
    image:
      repository: getmeili/meilisearch
      tag: v1.11.1
    resources:
      limits:
        memory: 128Mi
      requests:
        memory: 64Mi
    environment:
      MEILI_NO_ANALYTICS: 'true'
    storage:
      data: hoarder-meilisearch-data
compote3:
  enabled: true
  image:
    repository: ilvar/compote3
    tag: v0.2.0
  resources:
    limits:
      memory: 32Mi
  secrets:
    githubToken: ''
  config: "# Configuration for compote3\n\n# Additional application URLs (beyond k3s ingresses)\napplications:\n  - name: Gandi\n    url: https://admin.gandi.net/domain/08458030-153d-11ea-b8e3-00163e108e85/rkd.pw/records\n  - name: Tessie\n    url: https://dash.tessie.com\n  - name: Mailbox\n    url: https://app.mailbox.org/\n  - name: Trello\n    url: https://trello.com/b/YPlmZPom/personal\n\n\n# GitHub watched repositories\ngithub:\n  watcher: ilvar  # GitHub username to get watched repositories for\n"
  ingress:
    enabled: true
    hosts:
    - c.h.rkd.pw
    servicePort: 9000
paperless:
  enabled: true
  webserver:
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: latest
    resources:
      limits:
        memory: 1536Mi
      requests:
        memory: 768Mi
    environment:
      PAPERLESS_OCR_LANGUAGES: eng
      TZ: Europe/Dublin
      PAPERLESS_USE_SSL: 'false'
      PAPERLESS_FORGIVING_OCR: 'true'
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PAPERLESS_OCR_MODE: skip
      PAPERLESS_CONSUMER_DISABLE: 'true'
      PAPERLESS_WEBSERVER_WORKERS: 4
      PAPERLESS_URL: https://docs.h.rkd.pw
      USE_X_FORWARD_HOST: 'true'
      USE_X_FORWARD_PORT: 'true'
    storage:
      data: paperless-data
      media: paperless-media
      export: paperless-export
      consume: paperless-consume
  secrets:
    secretKey: ilvar
  redis:
    image:
      repository: redis
      tag: '6.0'
    resources:
      limits:
        memory: 256Mi
  ingress:
    enabled: true
    hosts:
    - docs.h.rkd.pw
    - docs.k.rkd.pw
    - d.h.rkd.pw
    - docs.z85
    servicePort: 8000
nextcloud:
  enabled: true
  app:
    image:
      repository: nextcloud
      tag: latest
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 256Mi
    user: 1000:1000
    environment:
      PUID: 1000
      PGID: 1000
      NEXTCLOUD_ADMIN_USER: ilvar
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: nextcloud-db
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.h.rkd.pw,nextcloud.z85,nc.h.rkd.pw
      OVERWRITEHOST: nextcloud.h.rkd.pw
      OVERWRITEPROTOCOL: https
    storage:
      data: nextcloud-data
  secrets:
    adminPassword: ''
    mysqlPassword: nextcloud
    mysqlRootPassword: nextcloud
  ingress:
    enabled: true
    hosts:
    - nextcloud.h.rkd.pw
    - nextcloud.k.rkd.pw
    - nextcloud.z85
    - nc.h.rkd.pw
    servicePort: 80
  db:
    image:
      repository: mariadb
      tag: '10.5'
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 128Mi
    user: 1000:1000
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      PUID: 1000
      PGID: 1000
    storage:
      size: 10Gi
kuma:
  enabled: true
  image:
    repository: louislam/uptime-kuma
    tag: latest
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
  storage:
    data: kuma-data
  ingress:
    enabled: true
    hosts:
    - kuma.h.rkd.pw
    - kuma.k.rkd.pw
    - k.h.rkd.pw
    servicePort: 3001
immich:
  enabled: true
  server:
    image:
      repository: ghcr.io/immich-app/immich-server
      tag: release
    resources:
      limits:
        memory: 1024Mi
      requests:
        memory: 512Mi
    environment:
      TZ: Europe/Dublin
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
      DB_HOSTNAME: immich-database
      REDIS_HOSTNAME: immich-redis
    storage:
      upload: immich-upload
  secrets:
    dbPassword: postgres
    postgresPassword: postgres
  machineLearning:
    image:
      repository: ghcr.io/immich-app/immich-machine-learning
      tag: release
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 256Mi
    storage:
      modelCache: immich-model-cache
  redis:
    image:
      repository: docker.io/valkey/valkey
      tag: 8-bookworm
      digest: sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    resources:
      limits:
        memory: 16Mi
      requests:
        memory: 16Mi
  database:
    image:
      repository: ghcr.io/immich-app/postgres
      tag: 14-vectorchord0.3.0-pgvectors0.2.0
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 256Mi
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: --data-checksums
    storage:
      size: 20Gi
      hostPath: /home/rkd/.docker/immich/postgres
  ingress:
    enabled: true
    hosts:
    - immich.h.rkd.pw
    - immich.k.rkd.pw
    servicePort: 2283
bugsink:
  enabled: true
  image:
    repository: bugsink/bugsink
    tag: latest
  resources:
    limits:
      memory: 768Mi
    requests:
      memory: 512Mi
  environment:
    CREATE_SUPERUSER: admin:admin
    PORT: '8000'
    BEHIND_HTTPS_PROXY: 'true'
    BASE_URL: https://bugsink.rkd.pw
  secrets:
    secretKey: ''
  storage:
    data: bugsink-data
  ingress:
    enabled: true
    hosts:
    - bugsink.k.rkd.pw
    - bugsink.rkd.pw
    servicePort: 8000
itTools:
  enabled: true
  image:
    repository: corentinth/it-tools
    tag: latest
  resources:
    limits:
      memory: 32Mi
    requests:
      memory: 16Mi
  ingress:
    enabled: true
    hosts:
    - it-tools.k.rkd.pw
    servicePort: 80
minifluxDb:
  enabled: true
  image:
    repository: postgres
    tag: 9.6.24-alpine
  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 64Mi
  environment:
    POSTGRES_USER: miniflux
    POSTGRES_DB: miniflux
  secrets:
    postgresPassword: 066a04f209
  storage:
    size: 1Gi
miniflux:
  enabled: true
  image:
    repository: miniflux/miniflux
    tag: 2.2.15
  resources:
    limits:
      memory: 64Mi
    requests:
      memory: 32Mi
  environment:
    DATABASE_URL: postgres://miniflux:066a04f209@miniflux-db:5432/miniflux?sslmode=disable
    RUN_MIGRATIONS: '1'
    CREATE_ADMIN: '1'
    ADMIN_USERNAME: ilvar
  secrets:
    adminPassword: jedi8947
  ingress:
    enabled: true
    hosts:
    - miniflux.rkd.pw
    - miniflux.k.rkd.pw
    servicePort: 8080
blog:
  enabled: true
  image:
    repository: ilvar/blog
    tag: latest
  resources:
    limits:
      memory: 512Mi
  ingress:
    enabled: true
    hosts:
    - blog.rkd.pw
    - blog.k.rkd.pw
    servicePort: 5000
rkdPw:
  enabled: true
  image:
    repository: ilvar/rkdpw
    tag: latest
  resources:
    limits:
      memory: 512Mi
  ingress:
    enabled: true
    hosts:
    - rkd.pw
    - rkd.k.rkd.pw
    - rkdpw.k.rkd.pw
    - www.rkd.pw
    servicePort: 5000
irishSchools:
  enabled: true
  image:
    repository: ilvar/irish-schools
    tag: latest
  resources:
    limits:
      memory: 64Mi
    requests:
      memory: 32Mi
  ingress:
    enabled: true
    hosts:
    - irish-schools.k.rkd.pw
    - irish-schools.rkd.pw
    servicePort: 5000
changes:
  enabled: true
  image:
    repository: dgtlmoon/changedetection.io
    tag: 0.51.4
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
  environment:
    BASE_URL: http://changes.k.rkd.pw
  storage:
    data: changes-data
  ingress:
    enabled: true
    hosts:
    - changes.k.rkd.pw
    servicePort: 5000
reloader:
  enabled: true
  reloader:
    watchGlobally: true
    ignoreNamespaces: ''
    ignoreSecrets: false
    ignoreConfigMaps: false
    logFormat: json
    resources:
      limits:
        memory: 64Mi
      requests:
        memory: 32Mi
        cpu: 50m
termix:
  enabled: true
  image:
    repository: ghcr.io/lukegus/termix
    tag: latest
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 128Mi
  environment:
    PORT: '8080'
  ports:
    http: 8080
  ingress:
    enabled: true
    hosts:
    - termix.h.rkd.pw
    - termix.k.rkd.pw
    servicePort: 8080
pinchflat:
  enabled: true
  image:
    repository: ghcr.io/kieraneglin/pinchflat
    tag: latest
  resources:
    limits:
      memory: 512Mi
  user: 1000:1000
  environment:
    TZ: America/New_York
  ports:
    http: 8945
  ingress:
    enabled: false
    hosts: []
    servicePort: 8945
tubearchivist:
  enabled: true
  image:
    repository: bbilly1/tubearchivist
    tag: v0.5.8
  resources:
    limits:
      memory: 1Gi
  user: 1000:1000
  environment:
    ES_URL: http://archivist-es:9200
    REDIS_CON: redis://archivist-redis:6379
    HOST_UID: '1000'
    HOST_GID: '1000'
    TA_HOST: http://tubearchivist.local:8000
    TZ: America/New_York
  ports:
    http: 8000
  secrets:
    TA_USERNAME: tubearchivist
    TA_PASSWORD: verysecret
    ELASTIC_PASSWORD: verysecret
  es:
    image:
      repository: bbilly1/tubearchivist-es
      tag: 8.18.2
    resources:
      limits:
        memory: 1536Mi
    environment:
      ES_JAVA_OPTS: -Xms768m -Xmx768m
  redis:
    image:
      repository: redis
      tag: 7.4.7-alpine
    resources:
      limits:
        memory: 256Mi
  ingress:
    enabled: false
    hosts: []
    servicePort: 8000
jitsi-meet:
  enabled: true
  publicURL: https://jitsi.h.rkd.pw
  enableAuth: true
  enableGuests: false
  web:
    replicaCount: 1
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 256Mi
        cpu: 250m
  prosody:
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 128Mi
        cpu: 100m
    persistence:
      enabled: true
      size: 3Gi
  jicofo:
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 256Mi
        cpu: 250m
  jvb:
    replicaCount: 1
    resources:
      limits:
        memory: 2Gi
      requests:
        memory: 1Gi
        cpu: 1000m
    useHostPort: true
    useNodeIP: true
  ingress:
    enabled: true
    className: ''
    hosts:
    - host: jitsi.h.rkd.pw
      paths:
      - path: /
        pathType: Prefix
    - host: jitsi.k.rkd.pw
      paths:
      - path: /
        pathType: Prefix
    tls:
    - secretName: homelab-wildcard-h-tls
      hosts:
      - jitsi.h.rkd.pw
      - jitsi.k.rkd.pw
