# Configuration for compote3

# Additional links
links:
  - name: RuTracker
    url: https://rutracker.org/forum/viewforum.php?f=635
  - name: Meduza
    url: https://meduza.io
  - name: Syncthing (web)
    url: https://syncthing.h.rkd.pw
  - name: Syncthing (desktop)
    url: http://localhost:8384
  # Add more links here
  # - name: Example
  #   url: https://example.com

# GitHub watched repositories
github:
  watcher: ilvar  # GitHub username to get watched repositories for

# Exclude apps from the list (case-insensitive)
exclusions:
  - compote3
  - rkd-pw

# Override app names and URLs
overrides:
  - name: rkd-compose-grafana
    new_name: grafana
    url: |
      https://grafana.k.rkd.pw/d/e0057f60-1041-4bff-9c0b-72b409765227/main?orgId=1&from=now-6h&to=now&timezone=browser&refresh=1m
