baseURL = 'https://blog.rkd.pw/'
languageCode = 'ru'
title = "RKD's"
theme = "noteworthy"
disqusShortname = "blog-rkd-pw"
relativeURLS=true

[Menus]
    [[Menus.main]]
        URL = "https://rkd.pw"
        Name = " Резюме"

    [[Menus.main]]
        URL = "https://www.linkedin.com/in/arcady-chumachenko-2634603/"
        Name = "Linkedin"

    [[Menus.main]]
        URL = "https://habr.com/ru/users/ilvar/"
        Name = "Хабр"
    