{{- if .Values.blog.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: blog
    spec:
      {{- if .Values.blog.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.blog.nodeSelector | nindent 8 }}
      {{- end }}
      {{- include "apps-chart.excludeNodeAffinity" . | nindent 6 }}
      containers:
      - name: blog
        image: "{{ .Values.blog.image.repository }}:{{ .Values.blog.image.tag }}"
        resources:
          limits:
            memory: {{ .Values.blog.resources.limits.memory }}
        ports:
        - containerPort: 5000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: blog
  labels:
    app: blog
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: blog
---
{{- if and .Values.blog.ingress.enabled (gt (len .Values.blog.ingress.hosts) 0) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog
  labels:
    app: blog
spec:
{{- if gt (len .Values.blog.ingress.hosts) 0 }}
  tls:
  - hosts:
{{- range .Values.blog.ingress.hosts }}
    - {{ . | quote }}
{{- end }}
    secretName: homelab-wildcard-h-tls
{{- end }}
  rules:
  {{- range .Values.blog.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blog
            port:
              number: {{ $.Values.blog.ingress.servicePort }}
  {{- end }}
{{- end }}
{{- end }}
