{{- if .Values.bugsink.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugsink
  labels:
    app: bugsink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bugsink
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: bugsink
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      containers:
      - name: bugsink
        image: "{{ .Values.bugsink.image.repository }}:{{ .Values.bugsink.image.tag }}"
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: bugsink-secrets
              key: secret-key
        - name: CREATE_SUPERUSER
          value: {{ .Values.bugsink.environment.CREATE_SUPERUSER | quote }}
        - name: PORT
          value: {{ .Values.bugsink.environment.PORT | quote }}
        - name: BEHIND_HTTPS_PROXY
          value: {{ .Values.bugsink.environment.BEHIND_HTTPS_PROXY | quote }}
        - name: BASE_URL
          value: {{ .Values.bugsink.environment.BASE_URL | quote }}
        resources:
          limits:
            memory: {{ .Values.bugsink.resources.limits.memory }}
        ports:
        - containerPort: {{ .Values.bugsink.environment.PORT | int }}
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /app/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.bugsink.storage.data }}
---
apiVersion: v1
kind: Service
metadata:
  name: bugsink
  labels:
    app: bugsink
spec:
  ports:
  - port: {{ .Values.bugsink.ingress.servicePort }}
    targetPort: {{ .Values.bugsink.environment.PORT | int }}
    protocol: TCP
  selector:
    app: bugsink
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.bugsink.storage.data }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{{- if and .Values.bugsink.enabled .Values.bugsink.ingress.enabled (gt (len .Values.bugsink.ingress.hosts) 0) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bugsink
  labels:
    app: bugsink
spec:
{{- if gt (len .Values.bugsink.ingress.hosts) 0 }}
  tls:
  - hosts:
{{- range .Values.bugsink.ingress.hosts }}
    - {{ . | quote }}
{{- end }}
    secretName: homelab-wildcard-h-tls
{{- end }}
  rules:
  {{- range .Values.bugsink.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bugsink
            port:
              number: {{ $.Values.bugsink.ingress.servicePort }}
  {{- end }}
{{- end }}
{{- end }}
