apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: kosmos-frontend
  namespace: flux-system
spec:
  image: docker.io/ilvar/kosmos-frontend
  interval: 60m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: kosmos-backend
  namespace: flux-system
spec:
  image: docker.io/ilvar/kosmos-backend
  interval: 60m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: kosmos-frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: kosmos-frontend
  policy:
    semver:
      range: ">=0.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: kosmos-backend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: kosmos-backend
  policy:
    semver:
      range: ">=0.0.0"