apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: rkd-compose
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  secretRef:
    name: github-credentials
  timeout: 60s
  url: https://github.com/ilvar/rkd-compose.git
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homelab
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./apps-chart
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: rkd-compose
        namespace: flux-system
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: homelab
  targetNamespace: default
  timeout: 10m0s
  upgrade:
    crds: CreateReplace
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: kosmos-frontend
  namespace: flux-system
spec:
  image: docker.io/ilvar/kosmos-frontend
  interval: 60m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: kosmos-backend
  namespace: flux-system
spec:
  image: docker.io/ilvar/kosmos-backend
  interval: 60m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: kosmos-frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: kosmos-frontend
  policy:
    semver:
      range: ">=0.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: kosmos-backend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: kosmos-backend
  policy:
    semver:
      range: ">=0.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: kosmos-images
  namespace: flux-system
spec:
  interval: 60m
  sourceRef:
    kind: GitRepository
    name: rkd-compose
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@rkd.pw
      messageTemplate: "chore(images): bump kosmos services to {{ .images }}"
    push:
      branch: main
  update:
    path: ./apps-chart
    strategy: Setters