apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlamp
  labels:
    app: headlamp
spec:
  tls:
  - hosts:
    - headlamp.h.rkd.pw
    - headlamp.k.rkd.pw
    secretName: homelab-wildcard-h-tls
  rules:
  - host: headlamp.h.rkd.pw
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homelab-headlamp
            port:
              number: 80
  - host: headlamp.k.rkd.pw
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homelab-headlamp
            port:
              number: 80