{{- if .Values.irishSchools.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: irish-schools
  labels:
    app: irish-schools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irish-schools
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: irish-schools
    spec:
      containers:
      - name: irish-schools
        image: "{{ .Values.irishSchools.image.repository }}:{{ .Values.irishSchools.image.tag }}"
        resources:
          limits:
            memory: {{ .Values.irishSchools.resources.limits.memory }}
        ports:
        - containerPort: 5000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: irish-schools
  labels:
    app: irish-schools
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: irish-schools
---
{{- if and .Values.irishSchools.ingress.enabled (gt (len .Values.irishSchools.ingress.hosts) 0) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: irish-schools
  labels:
    app: irish-schools
spec:
{{- if gt (len .Values.irishSchools.ingress.hosts) 0 }}
  tls:
  - hosts:
{{- range .Values.irishSchools.ingress.hosts }}
    - {{ . | quote }}
{{- end }}
    secretName: homelab-wildcard-h-tls
{{- end }}
  rules:
  {{- range .Values.irishSchools.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: irish-schools
            port:
              number: {{ $.Values.irishSchools.ingress.servicePort }}
  {{- end }}
{{- end }}
{{- end }}
