{{- if .Values.itTools.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  labels:
    app: it-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-tools
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: it-tools
    spec:
      {{- include "apps-chart.excludeNodeAffinity" . | nindent 6 }}
      containers:
      - name: it-tools
        image: "{{ .Values.itTools.image.repository }}:{{ .Values.itTools.image.tag }}"
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            memory: {{ .Values.itTools.resources.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: it-tools
  labels:
    app: it-tools
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: it-tools
---
{{- if and .Values.itTools.ingress.enabled (gt (len .Values.itTools.ingress.hosts) 0) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: it-tools
  labels:
    app: it-tools
spec:
{{- if gt (len .Values.itTools.ingress.hosts) 0 }}
  tls:
  - hosts:
{{- range .Values.itTools.ingress.hosts }}
    - {{ . | quote }}
{{- end }}
    secretName: homelab-wildcard-h-tls
{{- end }}
  rules:
  {{- range .Values.itTools.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: it-tools
            port:
              number: {{ $.Values.itTools.ingress.servicePort }}
  {{- end }}
{{- end }}
{{- end }}
