{{- if .Values.jackett.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  labels:
    app: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: jackett
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - hm60
{{- include "apps-chart.excludeNodeMatchExpressions" . | nindent 14 }}
      containers:
      - name: jackett
        image: "{{ .Values.jackett.image.repository }}:{{ .Values.jackett.image.tag }}"
        env:
        - name: PUID
          value: {{ .Values.jackett.environment.PUID | quote }}
        - name: PGID
          value: {{ .Values.jackett.environment.PGID | quote }}
        - name: TZ
          value: {{ .Values.jackett.environment.TZ | quote }}
        - name: AUTO_UPDATE
          value: {{ .Values.jackett.environment.AUTO_UPDATE | quote }}
        resources:
          limits:
            memory: {{ .Values.jackett.resources.limits.memory }}
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: config
        hostPath:
          path: /home/rkd/.nas/homelab/jackett/data
          type: DirectoryOrCreate
      - name: downloads
        hostPath:
          path: /home/rkd/.nas/Downloads
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: jackett
  labels:
    app: jackett
spec:
  ports:
  - port: 9117
    targetPort: 9117
    protocol: TCP
  selector:
    app: jackett
{{- if and .Values.jackett.enabled .Values.jackett.ingress.enabled (gt (len .Values.jackett.ingress.hosts) 0) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jackett
  labels:
    app: jackett
spec:
{{- if gt (len .Values.jackett.ingress.hosts) 0 }}
  tls:
  - hosts:
{{- range .Values.jackett.ingress.hosts }}
    - {{ . | quote }}
{{- end }}
    secretName: homelab-wildcard-h-tls
{{- end }}
  rules:
  {{- range .Values.jackett.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jackett
            port:
              number: {{ $.Values.jackett.ingress.servicePort }}
  {{- end }}
{{- end }}
{{- end }}
