{{- if .Values.jellyfin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - rkd-um560
      containers:
      - name: jellyfin
        image: "{{ .Values.jellyfin.image.repository }}:{{ .Values.jellyfin.image.tag }}"
        env:
        - name: JELLYFIN_PublishedServerUrl
          value: {{ .Values.jellyfin.environment.JELLYFIN_PublishedServerUrl | quote }}
        resources:
          limits:
            memory: {{ .Values.jellyfin.resources.limits.memory }}
        ports:
        - containerPort: {{ .Values.jellyfin.ports.http }}
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config
        - name: cache
          mountPath: /cache
        - name: nas
          mountPath: /nas
      securityContext:
        runAsUser: {{ include "apps-chart.userID" .Values.jellyfin.user | int }}
        runAsGroup: {{ include "apps-chart.groupID" .Values.jellyfin.user | int }}
      volumes:
      - name: config
        hostPath:
          path: /home/rkd/.docker/jellyfin/config
          type: DirectoryOrCreate
      - name: cache
        hostPath:
          path: /home/rkd/.docker/jellyfin/cache
          type: DirectoryOrCreate
      - name: nas
        hostPath:
          path: /home/rkd/.nas
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  ports:
  - port: {{ .Values.jellyfin.ports.http }}
    targetPort: {{ .Values.jellyfin.ports.http }}
    protocol: TCP
  selector:
    app: jellyfin
{{- if and .Values.jellyfin.enabled .Values.jellyfin.ingress.enabled (gt (len .Values.jellyfin.ingress.hosts) 0) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
{{- if gt (len .Values.jellyfin.ingress.hosts) 0 }}
  tls:
  - hosts:
{{- range .Values.jellyfin.ingress.hosts }}
    - {{ . | quote }}
{{- end }}
    secretName: homelab-wildcard-h-tls
{{- end }}
  rules:
  {{- range .Values.jellyfin.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyfin
            port:
              number: {{ $.Values.jellyfin.ingress.servicePort }}
  {{- end }}
{{- end }}
{{- end }}

