{{- $jitsi := index .Values "jitsi-meet" -}}
{{- if and $jitsi.enabled $jitsi.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jitsi-meet
  labels:
    app: jitsi-meet
spec:
  ingressClassName: {{ $jitsi.ingress.className | default "traefik" | quote }}
  tls:
  {{- range $jitsi.ingress.tls }}
  - secretName: {{ .secretName | quote }}
    hosts:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
  {{- range $jitsi.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path | quote }}
        pathType: {{ .pathType | default "Prefix" }}
        backend:
          service:
            name: {{ printf "%s-jitsi-meet-web" $.Release.Name | quote }}
            port:
              number: 80
      {{- end }}
  {{- end }}
{{- end }}
