{{- if .Values.miniflux.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: miniflux-db-secrets
  labels:
    app: miniflux-db
type: Opaque
stringData:
  postgres-password: {{ .Values.minifluxDb.secrets.postgresPassword | default "" | quote }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.minifluxDb.name | default "miniflux-db" }}
  labels:
    app: {{ .Values.minifluxDb.appLabel | default "miniflux-db" }}
spec:
  serviceName: {{ .Values.minifluxDb.name | default "miniflux-db" }}
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.minifluxDb.appLabel | default "miniflux-db" }}
  template:
    metadata:
      labels:
        app: {{ .Values.minifluxDb.appLabel | default "miniflux-db" }}
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      {{- include "apps-chart.excludeNodeAffinity" . | nindent 6 }}
      containers:
      - name: miniflux-db
        image: "{{ .Values.minifluxDb.image.repository }}:{{ .Values.minifluxDb.image.tag }}"
        env:
        - name: POSTGRES_USER
          value: {{ .Values.minifluxDb.environment.POSTGRES_USER | quote }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: miniflux-db-secrets
              key: postgres-password
        - name: POSTGRES_DB
          value: {{ .Values.minifluxDb.environment.POSTGRES_DB | quote }}
        resources:
          limits:
            memory: {{ .Values.minifluxDb.resources.limits.memory }}
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.minifluxDb.storage.size | default "1Gi" }}
---
apiVersion: v1
kind: Service
metadata:
  name: miniflux-db
  labels:
    app: miniflux-db
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: {{ .Values.minifluxDb.appLabel | default "miniflux-db" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: miniflux-secrets
  labels:
    app: miniflux
type: Opaque
stringData:
  admin-password: {{ .Values.miniflux.secrets.adminPassword | default "" | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
  labels:
    app: miniflux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniflux
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: miniflux
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      {{- include "apps-chart.excludeNodeAffinity" . | nindent 6 }}
      containers:
      - name: miniflux
        image: "{{ .Values.miniflux.image.repository }}:{{ .Values.miniflux.image.tag }}"
        env:
        - name: DATABASE_URL
          value: {{ .Values.miniflux.environment.DATABASE_URL | quote }}
        - name: RUN_MIGRATIONS
          value: {{ .Values.miniflux.environment.RUN_MIGRATIONS | quote }}
        - name: CREATE_ADMIN
          value: {{ .Values.miniflux.environment.CREATE_ADMIN | quote }}
        - name: ADMIN_USERNAME
          value: {{ .Values.miniflux.environment.ADMIN_USERNAME | quote }}
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: miniflux-secrets
              key: admin-password
        resources:
          limits:
            memory: {{ .Values.miniflux.resources.limits.memory }}
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: miniflux
  labels:
    app: miniflux
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: miniflux
---
{{- if and .Values.miniflux.ingress.enabled (gt (len .Values.miniflux.ingress.hosts) 0) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: miniflux
  labels:
    app: miniflux
spec:
{{- if gt (len .Values.miniflux.ingress.hosts) 0 }}
  tls:
  - hosts:
{{- range .Values.miniflux.ingress.hosts }}
    - {{ . | quote }}
{{- end }}
    secretName: homelab-wildcard-h-tls
{{- end }}
  rules:
  {{- range .Values.miniflux.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: miniflux
            port:
              number: {{ $.Values.miniflux.ingress.servicePort }}
  {{- end }}
{{- end }}
{{- end }}
