{{- if .Values.nodered.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
  labels:
    app: nodered
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nodered
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: k3s.io/hostname
                operator: In
                values:
                - rkd-um560
      containers:
      - name: nodered
        image: "{{ .Values.nodered.image.repository }}:{{ .Values.nodered.image.tag }}"
        resources:
          limits:
            memory: {{ .Values.nodered.resources.limits.memory }}
        ports:
        - containerPort: {{ .Values.nodered.ports.http }}
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
        - name: hass-media
          mountPath: /hass_media
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        securityContext:
          privileged: {{ .Values.nodered.privileged }}
      securityContext:
        runAsUser: {{ include "apps-chart.userID" .Values.nodered.user | int }}
        runAsGroup: {{ include "apps-chart.groupID" .Values.nodered.user | int }}
      volumes:
      - name: data
        hostPath:
          path: /home/rkd/.docker/node-red-1/user
          type: DirectoryOrCreate
      - name: hass-media
        hostPath:
          path: /home/rkd/.docker/hass_media
          type: DirectoryOrCreate
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File
---
apiVersion: v1
kind: Service
metadata:
  name: nodered
  labels:
    app: nodered
spec:
  ports:
  - port: {{ .Values.nodered.ports.http }}
    targetPort: {{ .Values.nodered.ports.http }}
    protocol: TCP
  selector:
    app: nodered
{{- if and .Values.nodered.enabled .Values.nodered.ingress.enabled (gt (len .Values.nodered.ingress.hosts) 0) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodered
  labels:
    app: nodered
spec:
  rules:
  {{- range .Values.nodered.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodered
            port:
              number: {{ $.Values.nodered.ingress.servicePort }}
  {{- end }}
{{- end }}
{{- end }}

