{{- if .Values.parrot.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parrot
  labels:
    app: parrot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parrot
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: parrot
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - rkd-um560
{{- include "apps-chart.excludeNodeMatchExpressions" . | nindent 14 }}
      containers:
      - name: parrot
        image: "{{ .Values.parrot.image.repository }}:{{ .Values.parrot.image.tag }}"
        resources:
          limits:
            memory: {{ .Values.parrot.resources.limits.memory }}
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        hostPath:
          path: /home/rkd/.docker/parrot/data
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: parrot
  labels:
    app: parrot
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: parrot
{{- if and .Values.parrot.enabled .Values.parrot.ingress.enabled (gt (len .Values.parrot.ingress.hosts) 0) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parrot
  labels:
    app: parrot
spec:
{{- if gt (len .Values.parrot.ingress.hosts) 0 }}
  tls:
  - hosts:
{{- range .Values.parrot.ingress.hosts }}
    - {{ . | quote }}
{{- end }}
    secretName: homelab-wildcard-h-tls
{{- end }}
  rules:
  {{- range .Values.parrot.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: parrot
            port:
              number: {{ $.Values.parrot.ingress.servicePort }}
  {{- end }}
{{- end }}
{{- end }}
