{{- if .Values.portainer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
  labels:
    app: portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - rkd-um560
      containers:
      - name: portainer
        image: "{{ .Values.portainer.image.repository }}:{{ .Values.portainer.image.tag }}"
        resources:
          limits:
            memory: {{ .Values.portainer.resources.limits.memory }}
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: data
          mountPath: /data
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: data
        hostPath:
          path: /home/rkd/.docker/portainer_data
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: portainer
  labels:
    app: portainer
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: portainer
{{- if and .Values.portainer.enabled .Values.portainer.ingress.enabled (gt (len .Values.portainer.ingress.hosts) 0) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portainer
  labels:
    app: portainer
spec:
  rules:
  {{- range .Values.portainer.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portainer
            port:
              number: {{ $.Values.portainer.ingress.servicePort }}
  {{- end }}
{{- end }}
{{- end }}

