{{- if .Values.radarr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: radarr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - hm60
{{- include "apps-chart.excludeNodeMatchExpressions" . | nindent 14 }}
      containers:
      - name: radarr
        image: "{{ .Values.radarr.image.repository }}:{{ .Values.radarr.image.tag }}"
        env:
        - name: PUID
          value: {{ .Values.radarr.environment.PUID | quote }}
        - name: PGID
          value: {{ .Values.radarr.environment.PGID | quote }}
        - name: TZ
          value: {{ .Values.radarr.environment.TZ | quote }}
        resources:
          limits:
            memory: {{ .Values.radarr.resources.limits.memory }}
        volumeMounts:
        - name: config
          mountPath: /config
        - name: movies
          mountPath: /movies
        - name: nas
          mountPath: /nas
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: config
        hostPath:
          path: /home/rkd/.local/homelab/radarr/data
          type: DirectoryOrCreate
      - name: movies
        hostPath:
          path: /home/rkd/.nas
          type: DirectoryOrCreate
      - name: nas
        hostPath:
          path: /home/rkd/.nas
          type: DirectoryOrCreate
      - name: downloads
        hostPath:
          path: /home/rkd/.nas/Downloads
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  ports:
  - port: 7878
    targetPort: 7878
    protocol: TCP
  selector:
    app: radarr
{{- if and .Values.radarr.enabled .Values.radarr.ingress.enabled (gt (len .Values.radarr.ingress.hosts) 0) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  labels:
    app: radarr
spec:
{{- if gt (len .Values.radarr.ingress.hosts) 0 }}
  tls:
  - hosts:
{{- range .Values.radarr.ingress.hosts }}
    - {{ . | quote }}
{{- end }}
    secretName: homelab-wildcard-h-tls
{{- end }}
  rules:
  {{- range .Values.radarr.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              number: {{ $.Values.radarr.ingress.servicePort }}
  {{- end }}
{{- end }}
{{- end }}
