{{- if .Values.vlsingle.enabled }}
apiVersion: operator.victoriametrics.com/v1
kind: VLSingle
metadata:
  name: {{ .Values.vlsingle.name | default "vlsingle" }}
  labels:
    app: vlsingle
spec:
  {{- if .Values.vlsingle.image }}
  image:
    repository: {{ .Values.vlsingle.image.repository }}
    tag: {{ .Values.vlsingle.image.tag }}
    {{- if .Values.vlsingle.image.pullPolicy }}
    pullPolicy: {{ .Values.vlsingle.image.pullPolicy }}
    {{- end }}
  {{- end }}
  {{- if .Values.vlsingle.retentionPeriod }}
  retentionPeriod: {{ .Values.vlsingle.retentionPeriod | quote }}
  {{- end }}
  {{- if .Values.vlsingle.resources }}
  resources:
    {{- toYaml .Values.vlsingle.resources | nindent 4 }}
  {{- end }}
  {{- if .Values.vlsingle.storage }}
  storage:
    resources:
      requests:
        storage: {{ .Values.vlsingle.storage.size }}
  {{- end }}
{{- end }}
