{{- if and .Values.vmagent.enabled .Values.vmagent.nodeScrape.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: {{ .Values.vmagent.nodeScrape.name | default "node-exporter" }}
  labels:
    app: vmagent
spec:
  {{- if .Values.vmagent.nodeScrape.selector }}
  selector:
    {{- toYaml .Values.vmagent.nodeScrape.selector | nindent 4 }}
  {{- end }}
  {{- if .Values.vmagent.nodeScrape.port }}
  port: {{ .Values.vmagent.nodeScrape.port | quote }}
  {{- end }}
  {{- if .Values.vmagent.nodeScrape.path }}
  path: {{ .Values.vmagent.nodeScrape.path | quote }}
  {{- end }}
  {{- if .Values.vmagent.nodeScrape.interval }}
  interval: {{ .Values.vmagent.nodeScrape.interval | quote }}
  {{- end }}
{{- end }}
