{{- if .Values.vmsingle.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: {{ .Values.vmsingle.name | default "vmsingle" }}
  labels:
    app: vmsingle
spec:
  {{- if .Values.vmsingle.image }}
  image:
    repository: {{ .Values.vmsingle.image.repository }}
    tag: {{ .Values.vmsingle.image.tag }}
    {{- if .Values.vmsingle.image.pullPolicy }}
    pullPolicy: {{ .Values.vmsingle.image.pullPolicy }}
    {{- end }}
  {{- end }}
  {{- if .Values.vmsingle.retentionPeriod }}
  retentionPeriod: {{ .Values.vmsingle.retentionPeriod | quote }}
  {{- end }}
  {{- if .Values.vmsingle.resources }}
  resources:
    {{- toYaml .Values.vmsingle.resources | nindent 4 }}
  {{- end }}
  {{- if .Values.vmsingle.storage }}
  storage:
    resources:
      requests:
        storage: {{ .Values.vmsingle.storage.size }}
  {{- end }}
{{- end }}
